apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bigdata
resources:
  - namespace.yaml
  - kafka.yaml
  - flink.yaml
  - doris.yaml
  - monitoring.yaml
commonLabels:
  app.kubernetes.io/part-of: bigdata-platform
