apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target: { kind: StatefulSet, name: kafka }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 5
  - target: { kind: StatefulSet, name: doris-be }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 5
  - target: { kind: Deployment, name: flink-taskmanager }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 5
commonLabels:
  environment: production
